### PR TITLE
Added support for cdi3.json and fix the bug caused by illegal mask

### PR DESCRIPTION
**Pull request by ShigemoriHakura**
The userdata3.json is not the cdi3.json.

### CODE REVIEW

**Comment by wada-at-live2d-com** [comment]
@ShigemoriHakura 
Thank you for pull request and investigation!

Certainly, Cubism SDK for Unity should support cdi3.json.

We accept your PR and will release the next version with this support as well as additional features!
Please wait for the support.

Sincerely,

**Comment by ShigemoriHakura** [comment]
When loading a model with illegal artmesh, the cubism viewer can load the model correctly but the Live2D unity sdk will just give a error.
The error before the commit
The error give by viewer 1
The error give by viewer 2
The model loaded by the viewer
The model loaded before the commit
The model loaded after the commit

**Comment by wada-at-live2d-com** [comment]
Hi, @ShigemoriHakura

We are checking to fix and reproduce illegal mask problem you presented.
Can you upload the model you used to check the problem?

**Comment by ShigemoriHakura** [comment]
> Hi, @ShigemoriHakura
> 
> We are checking to fix and reproduce illegal mask problem you presented.
> Can you upload the model you used to check the problem?

I’ve asked the owner of the model and he didn’t allow me to send the model. Sorry for that.

**Comment by wada-at-live2d-com** [comment]
@ShigemoriHakura 

Since we do not know the structure of the model, we too are having trouble confirming it. We have not been able to reproduce it either.
We would like you or someone you know to create the model data to reproduce, or we would like to exchange the model data via email.

**Comment by ShigemoriHakura** [comment]
> @ShigemoriHakura
> 
> Since we do not know the structure of the model, we too are having trouble confirming it.
> We have not been able to reproduce it either.
> We would like you or someone you know to create the model data to reproduce, or we would like to exchange the model data via email.

Can you give me the email address?

**Comment by wada-at-live2d-com** [comment]
@ShigemoriHakura 

Please use contact form to send it to us.
https://www.live2d.jp/eng/contact/?redirect=1
and choose it.
Individual or Business -> Using Live2D Products

**Comment by ShigemoriHakura** [comment]
> @ShigemoriHakura
> 
> Please use contact form to send it to us.
> https://www.live2d.jp/eng/contact/?redirect=1
> and choose it.
> Individual or Business -> Using Live2D Products

ok, sent.

**Comment by wada-at-live2d-com** [comment]
@ShigemoriHakura 

Thank you, I'll check my email.
Please wait for me to confirm.

**Comment by wada-at-live2d-com** [comment]
@ShigemoriHakura 

Your model has been verified to work.

The current release of Cubism SDK for Unity R2 has the problem, but the latest commit in this repository does not.

https://github.com/Live2D/CubismUnityComponents/commit/d33cefe9ddcb5be8487a431fa584c9b7e56682d9

Can you use this commit to check again?

**Comment by ShigemoriHakura** [comment]
Seems that commit fix the bug in another way.

**Comment by wada-at-live2d-com** [comment]
@ShigemoriHakura 

Thanks for the confirmation.
This fix for the incorrect mask has already been committed and will be incorporated into the production version.
Also, cdi3.json is being worked on to include the extension.

Unfortunately, this pull request will not be merged, but it helps Cubism SDK, so we will try to take your intentions into account.
You can proceed with the project as is with this fix.
It will be closed when we release the next version Cubism SDK.

Sincerely,

**Comment by wada-at-live2d-com** [comment]
@ShigemoriHakura 

Cubism 4 SDK for Unity R3 has been released today.
This product includes the ability to use cdi3.json and support for illegal mask input.
Please try it out.

https://github.com/Live2D/CubismUnityComponents/tree/4-r.3

**Pull request closed without merging**
